#!/usr/bin/env bash
# scripts/lib/cpu-canary.sh -- RFC-005 slice 10: the platform-identity
# canary for scripts/test.sh's --cpu leg (today's only supported value,
# i386 -- the 32-bit multilib matrix leg). RFC-005 Part B names this
# canary literally: "Identity canary: pointers are 4 bytes." -- unlike
# scripts/lib/toolchain-canary.sh / sanitizer-canary.sh (which infer an
# identity fact from Nim's own --listCmd text -- "did the C compile line
# carry the flag/name we expect"), the fact this leg needs to prove is a
# RUNTIME property of the compiled binary, not merely something visible
# in the compile command line: a --cpu:i386 invocation that silently fell
# back to a 64-bit build (a misconfigured backend, a stale nimcache, a
# copy-paste that dropped --passC:-m32) would still show "-m32" nowhere
# near reality unless something actually EXECUTES under the resulting
# binary and checks. So this canary compiles and RUNS a tiny throwaway
# probe (regenerated every invocation, not part of the committed test
# suite) that `doAssert`s sizeof(pointer) == 4 and sizeof(int) == 4 (Nim's
# `int` is pointer-sized on every backend Nim supports, so the second
# assertion is the direct corollary of the first, not a separate claim) --
# a failing assertion aborts the probe binary with a nonzero exit, which
# this script treats as a hard canary failure. This is deliberately an
# EXTRA compile (unlike toolchain-canary.sh/sanitizer-canary.sh, which
# reuse the suite's own first-file compile) since the probe's whole job is
# proving a fact about program EXECUTION, and the suite's own first file
# is a full unittest binary with its own control flow this script has no
# business hooking a canary assertion into.
#
# On top of the runtime check, this script ALSO re-uses
# toolchain-canary.sh's own --listCmd-grep technique to prove the C
# compile line genuinely carried `-m32` (not merely that the resulting
# binary happens to size pointers at 4 bytes some other way) and that the
# expected C compiler was actually invoked -- the same "read Nim's own
# record of what it executed, not just the flag we handed it" posture
# every other canary in this codebase holds.
#
# Usage: cpu-canary.sh <expected-cc-name> nim c [--cc:<name>] --cpu:<cpu> --passC:-m32 --passL:-m32 [more flags...]
#   e.g. cpu-canary.sh gcc nim c --cpu:i386 --passC:-m32 --passL:-m32
# The caller supplies everything EXCEPT --listCmd/-f/-r/the target file --
# this script owns the probe file (see above) and appends those itself,
# so a caller cannot accidentally point this canary at a real test file
# instead of the probe.
set -uo pipefail

expect_cc="$1"
shift

mkdir -p build
probe="build/cpu_canary_probe.nim"
cat > "$probe" <<'NIM'
# Regenerated by scripts/lib/cpu-canary.sh on every run -- not part of the
# committed test suite (build/ is gitignored). Asserts, at RUNTIME, the
# exact fact RFC-005 Part B names for this leg: pointers are 4 bytes.
doAssert sizeof(pointer) == 4, "cpu canary: expected sizeof(pointer) == 4, got " & $sizeof(pointer)
doAssert sizeof(int) == 4, "cpu canary: expected sizeof(int) == 4, got " & $sizeof(int)
echo "cpu canary probe: sizeof(pointer)=", sizeof(pointer), " sizeof(int)=", sizeof(int)
NIM

out="$("$@" --listCmd -f -r "$probe" 2>&1)"
rc=$?
echo "$out"

if [[ "$rc" -ne 0 ]]; then
  echo "cpu canary: FAIL -- the probe compile/run itself failed (see output above) -- either the build broke or the doAssert fired (wrong pointer/int width)." >&2
  exit "$rc"
fi

# Same C-compiler-invocation-line match as toolchain-canary.sh (see that
# script's header for the exact pattern rationale).
line="$(printf '%s\n' "$out" | grep -m1 -E '(^|[ /\t])(gcc|clang)(\.exe)?(-[0-9.]+)?([ \t]|$)')"
echo "cpu canary: resolved C compiler invocation: ${line:-<none found in --listCmd output>}"

case "$line" in
  *"$expect_cc"*)
    echo "cpu canary: PASS -- confirmed Nim actually invoked '$expect_cc'."
    ;;
  *)
    echo "cpu canary: FAIL -- expected the C compiler invocation to contain '$expect_cc', but observed: $line" >&2
    exit 1
    ;;
esac

case "$line" in
  *"-m32"*)
    echo "cpu canary: PASS -- confirmed the C compile invocation carries -m32."
    ;;
  *)
    echo "cpu canary: FAIL -- expected the C compile invocation to carry -m32, but observed: $line" >&2
    exit 1
    ;;
esac

echo "cpu canary: PASS -- the probe binary ran and confirmed sizeof(pointer) == 4 and sizeof(int) == 4 at runtime."
