#!/usr/bin/env bash
# scripts/lib/endian-canary.sh -- RFC-005 slice 25 (Nightly part 2: s390x
# big-endian, A4). The platform-identity canary for scripts/test.sh's
# `--cpu s390x` leg, the cross-compiled/QEMU-run sibling of
# scripts/lib/cpu-canary.sh's `--cpu i386` canary. RFC-005 Part B's own
# text for this leg: "an endianness canary test that fails if the binary
# is actually little-endian." Like cpu-canary.sh, this is deliberately a
# RUNTIME probe, not merely a --listCmd text inference: Nim's own
# compile-time `cpuEndian` constant is resolved from the TARGET CPU the
# compiler was told to build for (`--cpu:s390x`), so a `doAssert
# cpuEndian == bigEndian` alone would tautologically pass even if
# something upstream silently fell back to a little-endian build (a
# misconfigured --cpu flag, a stale nimcache reusing an amd64 object) --
# exactly the same class of "the flag was accepted but reality diverged"
# risk cpu-canary.sh's own header names for --cpu:i386. So this probe
# additionally copies a KNOWN 32-bit word's raw bytes into an array and
# asserts their IN-MEMORY order is big-endian (0x01020304 must read back
# as bytes [0x01, 0x02, 0x03, 0x04], not [0x04, 0x03, 0x02, 0x01]) -- a
# fact about the actual compiled-and-executed binary, not merely about
# what Nim's frontend believes it targeted.
#
# Unlike cpu-canary.sh, the compiled probe cannot be executed directly on
# this (amd64) host at all -- it is a genuine s390x ELF binary. So this
# script never passes `-r` to `nim c`; it compiles the probe, then
# executes it itself via the caller-supplied RUN-WITH command (the same
# wrapper scripts/test.sh's own per-file loop uses for every real suite
# file under --cpu s390x -- see that script's own header comment for the
# "--run-with wrapper hook" design). This script owns neither qemu nor
# the sysroot path; the caller decides both and hands them over as one
# opaque, already-quoted command string.
#
# On top of the two runtime facts above, this script ALSO re-uses
# cpu-canary.sh's/toolchain-canary.sh's own --listCmd-grep technique to
# prove the C compile line genuinely invoked the expected CROSS compiler
# (s390x-suse-linux-gcc, not a native gcc silently substituted) -- the
# same "read Nim's own record of what it executed, not just the flag we
# handed it" posture every canary in this codebase holds.
#
# Usage:
#   endian-canary.sh <expect-cc-substring> <run-with-command> nim c [flags...]
#     e.g. endian-canary.sh s390x-suse-linux-gcc \
#            "qemu-s390x -L /usr/s390x-suse-linux/sys-root" \
#            nim c --cpu:s390x --os:linux \
#            --gcc.exe:s390x-suse-linux-gcc --gcc.linkerexe:s390x-suse-linux-gcc
#
# <run-with-command> is handed to `eval` with the probe's output path
# appended -- same "opaque, caller-owned wrapper string" convention
# scripts/test.sh's own --run-with hook uses, so both call sites agree on
# the exact same qemu invocation with no risk of drift between them.
#
# The caller supplies everything EXCEPT --listCmd/-f/-o/the probe file --
# this script owns the probe file and the output path (see above) and
# appends those itself, so a caller cannot accidentally point this canary
# at a real test file instead of the probe.
#
# RED-PATH DEMONSTRATION (this slice's own DoD): calling this script with
# a NATIVE (non-cross) compiler and no run-with wrapper at all --
# `endian-canary.sh gcc "" nim c` -- compiles the identical probe for the
# native amd64 target and runs it directly; the `doAssert cpuEndian ==
# bigEndian` (and the big-endian-byte-order check) both fire on a real
# little-endian host, proving this canary genuinely distinguishes
# little-endian from big-endian rather than passing unconditionally. See
# docs/rfc-005-validation-infra.handoff.md's slice 25 entry for the real
# CI run id this was demonstrated against.
set -uo pipefail

expect_cc="$1"
shift
run_with="$1"
shift

mkdir -p build
probe="build/endian_canary_probe.nim"
out_bin="build/endian_canary_probe_bin"
cat > "$probe" <<'NIM'
# Regenerated by scripts/lib/endian-canary.sh on every run -- not part of
# the committed test suite (build/ is gitignored). Asserts, at RUNTIME,
# the exact fact RFC-005 Part B names for this leg: the binary is
# genuinely big-endian, not merely compiled with a flag that claims so.
var word: uint32 = 0x01020304'u32
var bytes: array[4, byte]
copyMem(addr bytes[0], addr word, 4)
doAssert cpuEndian == bigEndian, "endian canary: expected cpuEndian == bigEndian, got " & $cpuEndian
doAssert bytes[0] == 0x01'u8 and bytes[1] == 0x02'u8 and bytes[2] == 0x03'u8 and bytes[3] == 0x04'u8,
  "endian canary: expected big-endian in-memory byte order [01 02 03 04], got " & $bytes
doAssert sizeof(pointer) == 8, "endian canary: expected sizeof(pointer) == 8, got " & $sizeof(pointer)
echo "endian canary probe: cpuEndian=", cpuEndian, " bytes=", bytes, " sizeof(pointer)=", sizeof(pointer)
NIM

compile_out="$("$@" --listCmd -f -o:"$out_bin" "$probe" 2>&1)"
compile_rc=$?
echo "$compile_out"

if [[ "$compile_rc" -ne 0 ]]; then
  echo "endian canary: FAIL -- the probe compile itself failed (see output above)." >&2
  exit "$compile_rc"
fi

# Same C-compiler-invocation-line match as cpu-canary.sh/toolchain-canary.sh.
line="$(printf '%s\n' "$compile_out" | grep -m1 -E '(^|[ /\t])([a-zA-Z0-9_.-]*gcc|[a-zA-Z0-9_.-]*clang)(\.exe)?(-[0-9.]+)?([ \t]|$)')"
echo "endian canary: resolved C compiler invocation: ${line:-<none found in --listCmd output>}"

case "$line" in
  *"$expect_cc"*)
    echo "endian canary: PASS -- confirmed Nim actually invoked '$expect_cc'."
    ;;
  *)
    echo "endian canary: FAIL -- expected the C compiler invocation to contain '$expect_cc', but observed: $line" >&2
    exit 1
    ;;
esac

# --- Execute the compiled probe via the caller-supplied run-with wrapper.
# An EMPTY run_with means "run natively" -- the red-path demonstration
# above, and also the ordinary in-band case for a non-cross canary call
# (not used by scripts/test.sh's own --cpu s390x path, which always
# supplies a real qemu wrapper, but kept general rather than special-
# cased so the red-path demo IS a real, unmodified invocation of this
# same script, not a separate code path).
if [[ -n "$run_with" ]]; then
  run_out="$(eval "$run_with $out_bin" 2>&1)"
else
  run_out="$("$out_bin" 2>&1)"
fi
run_rc=$?
echo "$run_out"

if [[ "$run_rc" -ne 0 ]]; then
  echo "endian canary: FAIL -- the probe binary exited nonzero (a doAssert fired, or the run-with wrapper itself failed to execute it -- see output above)." >&2
  exit "$run_rc"
fi

case "$run_out" in
  *"cpuEndian=bigEndian"*)
    echo "endian canary: PASS -- confirmed the probe binary genuinely ran as big-endian (cpuEndian + real in-memory byte order + sizeof(pointer)==8, all asserted at runtime)."
    ;;
  *)
    echo "endian canary: FAIL -- expected the probe's own stdout to report cpuEndian=bigEndian, but observed: $run_out" >&2
    exit 1
    ;;
esac
