#!/usr/bin/env python3
"""Generate SHA-512 padding-boundary test vectors for sello (RFC-006).

The NIST CAVP corpus (SHA512ShortMsg.rsp / SHA512LongMsg.rsp) does not
reliably cover the exact padding-threshold lengths sello's SHA-512 core
needs deterministic coverage for: ShortMsg only spans 0-128 bytes
(0-1024 bits), and LongMsg is a sparse curated set that cannot be assumed
to contain 129/239/240-byte messages. This script is the named source of
truth for those lengths, using Python's stdlib `hashlib.sha512` as an
independent second implementation -- no dependency on sello's own
arithmetic, no shared code with the Nim port -- the same
independent-oracle register `gen_scmuladd_vectors.py` established for
scMulAdd (Python bigints there, Python's own audited hashlib here).

Message construction is deterministic, not random: an n-byte message is
bytes(i % 256 for i in range(n)) -- a simple, reproducible byte pattern
that varies across the message, rather than re-testing an all-zero corner
case CAVP's own vectors already cover.

Lengths covered (see RFC-006's Design/slice 1 note): both sides of the
single-block/two-block padding boundary (111/112 bytes -- 112 is the
first length that needs a second block, since FIPS 180-4 padding always
reserves the final 16 bytes of a block for the 128-bit length field), a
two-block message one byte either side of a full 128-byte block plus the
block boundary itself (127/128/129), and the analogous pair one block up
(239/240), plus the small-input edge (0/1).

Output: tests/vectors/sha512_boundary_test.json, checked in alongside
this script (the scmuladd_test.json precedent). Not consumed until slice
1b (no `sha512.nim` exists yet in slice 1a -- `test_sha512.nim` only
sanity-checks this file's own shape in that slice).

Usage:
    python3 tests/vectors/gen_sha512_boundary_vectors.py > tests/vectors/sha512_boundary_test.json

Run from the repository root (or adjust the redirect path accordingly).
"""
import hashlib
import json

LENGTHS = [0, 1, 111, 112, 127, 128, 129, 239, 240]


def message_for(n: int) -> bytes:
    return bytes(i % 256 for i in range(n))


def vector(n: int) -> dict:
    msg = message_for(n)
    digest = hashlib.sha512(msg).digest()
    assert len(digest) == 64
    return {
        "length": n,
        "msg": msg.hex(),
        "digest": digest.hex(),
    }


def main() -> None:
    vectors = [vector(n) for n in LENGTHS]
    assert len(vectors) == len(LENGTHS)
    doc = {
        "description": (
            "SHA-512 padding-boundary test vectors: messages of "
            + ", ".join(str(n) for n in LENGTHS) +
            " bytes, byte i of an n-byte message equal to i mod 256. "
            "Generated by gen_sha512_boundary_vectors.py using Python's "
            "hashlib.sha512 as an independent second implementation."
        ),
        "vectors": vectors,
    }
    print(json.dumps(doc, indent=2))


if __name__ == "__main__":
    main()
