#!/usr/bin/env python3
"""Generate test vectors for sello's scMulAdd (ref10 sc_muladd port).

scMulAdd computes s = (a*b + c) mod L on 32-byte little-endian scalars,
where L is the ed25519 subgroup order. This script is the independent
oracle: it uses Python's native arbitrary-precision integers (no crypto
library, no dependency on sello's own arithmetic) to compute expected
results, so a bug shared between the Nim port and this script cannot
cancel out and pass.

Output: tests/vectors/scmuladd_test.json, checked in alongside this
script (same pattern as the vendored Wycheproof JSON vectors). Contains:

  - "fixed": all 27 joint combinations of (a, b, c) in {0, 1, L-1}^3 --
    deterministic, not RNG-derived, listed explicitly for readability.
  - "random": a seeded-RNG batch of random triples in [0, L). Re-running
    this script regenerates byte-for-byte the same file, since Python's
    random.Random(seed) is used (not the system CSPRNG).

Usage:
    python3 tests/vectors/gen_scmuladd_vectors.py > tests/vectors/scmuladd_test.json

Run from the repository root (or adjust the redirect path accordingly).
"""
import json
import random

# ed25519 subgroup order, RFC 8032 section 2 / 5.1.
L = 2**252 + 27742317777372353535851937790883648493

RNG_SEED = 20260201  # arbitrary, fixed -- reruns must reproduce this file
RANDOM_COUNT = 1000


def to_hex_le(x: int, nbytes: int = 32) -> str:
    return x.to_bytes(nbytes, "little").hex()


def vector(a: int, b: int, c: int) -> dict:
    expected = (a * b + c) % L
    return {
        "a": to_hex_le(a),
        "b": to_hex_le(b),
        "c": to_hex_le(c),
        "expected": to_hex_le(expected),
    }


def fixed_vectors() -> list:
    values = [("0", 0), ("1", 1), ("L-1", L - 1)]
    out = []
    for an, a in values:
        for bn, b in values:
            for cn, c in values:
                v = vector(a, b, c)
                v["comment"] = f"(a,b,c) = ({an}, {bn}, {cn})"
                out.append(v)
    assert len(out) == 27
    return out


def random_vectors(seed: int, count: int) -> list:
    rng = random.Random(seed)
    out = []
    for _ in range(count):
        a = rng.randrange(0, L)
        b = rng.randrange(0, L)
        c = rng.randrange(0, L)
        out.append(vector(a, b, c))
    return out


def main() -> None:
    doc = {
        "description": (
            "scMulAdd test vectors: s = (a*b + c) mod L, 32-byte "
            "little-endian scalars. Generated by gen_scmuladd_vectors.py "
            "using Python bigints as an independent oracle."
        ),
        "l": to_hex_le(L),
        "fixed": fixed_vectors(),
        "random": {
            "seed": RNG_SEED,
            "count": RANDOM_COUNT,
            "vectors": random_vectors(RNG_SEED, RANDOM_COUNT),
        },
    }
    print(json.dumps(doc, indent=2))


if __name__ == "__main__":
    main()
