## scMulAdd: s = (a*b + c) mod L, ref10 sc_muladd port (scalar.nim).
##
## Vectors: all 27 joint combinations of (a, b, c) in {0, 1, L-1}^3, plus
## >=1000 random triples in [0, L). Both sets are generated by the checked-in
## oracle tests/vectors/gen_scmuladd_vectors.py (Python bigints, independent
## of sello's own arithmetic) into tests/vectors/scmuladd_test.json.

import std/[unittest, json, strutils]
import nimcrypto/sha2
import sello/scalar
import sello/field

const rawVectors = staticRead("../vectors/scmuladd_test.json")

proc hexToArray32(s: string): array[32, byte] =
  doAssert s.len == 64
  for i in 0 ..< 32:
    result[i] = byte(parseHexInt(s[2 * i .. 2 * i + 1]))

proc cachedEncode(c: GeCached; invTwo: Fe): array[32, byte] =
  ## Canonical compressed encoding of the point cached in `c`, recovering
  ## affine X = (yPlusX - yMinusX)/2, Y = (yPlusX + yMinusX)/2 and reusing
  ## pointEncode (which only reads x/y/z, never t) to normalize away the
  ## projective Z-scaling. Needed because two different computational
  ## paths to the same point (this table's incremental doubling/addition
  ## vs. scalarmult's 4-bit-window algorithm) generally land on different,
  ## equally-valid (X:Y:Z:T) representatives — raw limb/struct equality
  ## between them would be a false negative, not a real correctness check.
  var p: GeP3
  var sum, diff: Fe
  feAdd(sum, c.yPlusX, c.yMinusX)
  feSub(diff, c.yPlusX, c.yMinusX)
  feMul(p.y, sum, invTwo)
  feMul(p.x, diff, invTwo)
  p.z = c.z
  pointEncode(p)

suite "scMulAdd":
  test "1*1 + 0 = 1 (RED anchor vector)":
    var a, b, c, expected: array[32, byte]
    a[0] = 1
    b[0] = 1
    expected[0] = 1
    check scMulAdd(a, b, c) == expected

  test "27 fixed joint combinations of (a, b, c) in {0, 1, L-1}^3":
    let root = parseJson(rawVectors)
    var checked = 0
    for v in root["fixed"]:
      let a = hexToArray32(v["a"].getStr)
      let b = hexToArray32(v["b"].getStr)
      let c = hexToArray32(v["c"].getStr)
      let expected = hexToArray32(v["expected"].getStr)
      check scMulAdd(a, b, c) == expected
      inc checked
    check checked == 27

  test "random triples from the seeded python3 oracle":
    let root = parseJson(rawVectors)
    let randomGroup = root["random"]
    var checked = 0
    for v in randomGroup["vectors"]:
      let a = hexToArray32(v["a"].getStr)
      let b = hexToArray32(v["b"].getStr)
      let c = hexToArray32(v["c"].getStr)
      let expected = hexToArray32(v["expected"].getStr)
      check scMulAdd(a, b, c) == expected
      inc checked
    check checked == randomGroup["count"].getInt
    check checked >= 1000

suite "GeBaseTable (RFC-001 slice 3)":
  test "row 0, column 0 is the base point B itself (RED anchor vector)":
    let b = geBasePoint()
    var expected: GeCached
    geP3ToCached(expected, b)
    check GeBaseTable[0][0] == expected

  test "every entry equals the runtime-computed multiple of B (standing guard)":
    ## GeBaseTable[i][j] must equal (j+1) * 16^(2*i) * B = (j+1) * 256^i * B,
    ## checked independently against the vartime scalarmult already proven
    ## against RFC 8032 + Wycheproof. This repo has no CI, so this assertion
    ## re-verifies the compile-time table on every `nimble test` run rather
    ## than trusting the const-eval once. Compared via canonical point
    ## encoding (cachedEncode), not raw struct equality — see its doc
    ## comment for why.
    let b = geBasePoint()
    var two = Fe(limbs: [2'i32, 0, 0, 0, 0, 0, 0, 0, 0, 0])
    var invTwo: Fe
    feInvert(invTwo, two)
    var checked = 0
    for i in 0..<32:
      for j in 1..8:
        var scalarBytes: array[32, byte]
        scalarBytes[i] = byte(j)  # little-endian encoding of j * 256^i
        var refP3: GeP3
        scalarmult(refP3, scalarBytes, b)
        check cachedEncode(GeBaseTable[i][j - 1], invTwo) == pointEncode(refP3)
        inc checked
    check checked == 32 * 8

suite "cmovCached (RFC-001 slice 3)":
  test "digit 0 selects the identity, with no special case":
    var r: GeCached
    cmovCached(r, GeBaseTable[0], 0)
    check r.yPlusX == FeOne
    check r.yMinusX == FeOne
    check r.z == FeOne
    check r.t2d == FeZero

  test "positive digits 1..8 select the matching table entry unchanged":
    for digit in 1..8:
      var r: GeCached
      cmovCached(r, GeBaseTable[0], int32(digit))
      check r == GeBaseTable[0][digit - 1]

  test "negative digits -1..-8 select the matching entry, negated":
    for digit in -8 .. -1:
      var r: GeCached
      cmovCached(r, GeBaseTable[0], int32(digit))
      let src = GeBaseTable[0][(-digit) - 1]
      var expectedT2d: Fe
      feNeg(expectedT2d, src.t2d)
      check r.yPlusX == src.yMinusX
      check r.yMinusX == src.yPlusX
      check r.z == src.z
      check r.t2d == expectedT2d

  test "every row of GeBaseTable agrees with cmovCached across all digits -8..8":
    for row in 0..<32:
      for digit in -8 .. 8:
        var r: GeCached
        cmovCached(r, GeBaseTable[row], int32(digit))
        if digit == 0:
          check r.yPlusX == FeOne
          check r.yMinusX == FeOne
          check r.z == FeOne
          check r.t2d == FeZero
        elif digit > 0:
          check r == GeBaseTable[row][digit - 1]
        else:
          let src = GeBaseTable[row][(-digit) - 1]
          var expectedT2d: Fe
          feNeg(expectedT2d, src.t2d)
          check r.yPlusX == src.yMinusX
          check r.yMinusX == src.yPlusX
          check r.z == src.z
          check r.t2d == expectedT2d

# ---------------------------------------------------------------------------
# geScalarmultBase (RFC-001 slice 4)
#
# Precondition under test throughout: bit 255 of the scalar clear — the
# WHOLE precondition (see scalar.nim's doc comment on recodeScalarRadix16).
# Both scalar domains that real signing exercises are covered:
#   - clamped secret-scalar shape (bit 255 clear, bit 254 set): RFC seed,
#     random clamped scalars, and the maximal clamped scalar (top byte
#     0x7F, the final-carry boundary).
#   - r-shaped nonces (reduced mod L, top three bits always clear since
#     L < 2^253): random reduced values and values just below L (the
#     bit-252 boundary region, L's own highest set bit).
# Every case is checked against the existing vartime `scalarmult` on the
# base point via pointEncode, not raw GeP3/GeCached equality — two
# algorithms reaching the same point generally land on different, equally
# valid projective representatives (same false-negative trap noted on the
# GeBaseTable standing-guard test above).
# ---------------------------------------------------------------------------

proc refBaseMultEncoded(s: array[32, byte]): array[32, byte] =
  var p: GeP3
  scalarmult(p, s, geBasePoint())
  pointEncode(p)

proc prngScalar32(counter: uint64): array[32, byte] =
  ## Deterministic pseudorandom 32 bytes for test-vector generation only —
  ## not used for anything security-sensitive. SHA-512 counter mode so a
  ## failing case reproduces exactly from the printed counter.
  var counterBytes: array[8, byte]
  for i in 0 ..< 8:
    counterBytes[i] = byte((counter shr (8 * i)) and 0xFF'u64)
  var sha: sha512
  sha.init()
  sha.update(counterBytes)
  var digest: array[64, byte]
  sha.finish(digest)
  for i in 0 ..< 32: result[i] = digest[i]

proc prngReducedScalar32(counter: uint64): array[32, byte] =
  ## A random-looking scalar strictly < L, exactly the shape a real nonce
  ## r = scReduce(SHA-512(...)) has: top three bits always clear.
  var wide: array[64, byte]
  let lo = prngScalar32(2 * counter)
  let hi = prngScalar32(2 * counter + 1)
  for i in 0 ..< 32: wide[i] = lo[i]
  for i in 0 ..< 32: wide[32 + i] = hi[i]
  scReduce(result, wide)

proc decrementLE(b: array[32, byte]; amount: int): array[32, byte] =
  ## b - amount, treating b as little-endian; amount is small enough
  ## (< 256) that at most one borrow ever propagates past the first limb
  ## in the vectors this file constructs from L.
  result = b
  var borrow = amount
  var i = 0
  while borrow > 0:
    doAssert i < 32
    let cur = int(result[i]) - borrow
    if cur < 0:
      result[i] = byte(cur + 256)
      borrow = 1
    else:
      result[i] = byte(cur)
      borrow = 0
    inc i

suite "geScalarmultBase (RFC-001 slice 4)":
  test "[1]B equals the base point itself (RED anchor vector)":
    var s: array[32, byte]
    s[0] = 1
    check pointEncode(geScalarmultBase(s)) == pointEncode(geBasePoint())

  test "clamped domain: RFC 8032 test-vector-1 seed, expanded and clamped":
    # RFC 8032 Section 7.1 TEST 1 secret key seed (also tv1_sk in
    # test_ed25519.nim) — a real clamped scalar `a` as `sign` will derive
    # it: a = clampScalar(SHA-512(seed)[0..31]).
    let seed: array[32, byte] = [
      0x9d'u8, 0x61, 0xb1, 0x9d, 0xef, 0xfd, 0x5a, 0x60,
      0xba, 0x84, 0x4a, 0xf4, 0x92, 0xec, 0x2c, 0xc4,
      0x44, 0x49, 0xc5, 0x69, 0x7b, 0x32, 0x69, 0x19,
      0x70, 0x3b, 0xac, 0x03, 0x1c, 0xae, 0x7f, 0x60
    ]
    var sha: sha512
    sha.init()
    sha.update(seed)
    var expanded: array[64, byte]
    sha.finish(expanded)
    var a: array[32, byte]
    for i in 0 ..< 32: a[i] = expanded[i]
    clampScalar(a)
    check pointEncode(geScalarmultBase(a)) == refBaseMultEncoded(a)

  test "clamped domain: 100 random clamped scalars match vartime scalarmult":
    var checked = 0
    for i in 0'u64 ..< 100:
      var s = prngScalar32(i)
      clampScalar(s)
      check pointEncode(geScalarmultBase(s)) == refBaseMultEncoded(s)
      inc checked
    check checked == 100

  test "clamped domain: maximal clamped scalar (top byte 0x7F, final-carry boundary)":
    var s: array[32, byte]
    for i in 0 ..< 32: s[i] = 0xFF
    clampScalar(s)
    check s[0] == 0xF8
    check s[31] == 0x7F
    check pointEncode(geScalarmultBase(s)) == refBaseMultEncoded(s)

  test "r-shaped domain: 100 random reduced-mod-L scalars match vartime scalarmult":
    var checked = 0
    for i in 0'u64 ..< 100:
      let r = prngReducedScalar32(i)
      check scIsCanonical(r)
      check pointEncode(geScalarmultBase(r)) == refBaseMultEncoded(r)
      inc checked
    check checked == 100

  test "r-shaped domain: values just below L (bit-252 boundary region)":
    for amount in [1, 2, 3, 17, 255]:
      let r = decrementLE(L, amount)
      check scIsCanonical(r)
      check pointEncode(geScalarmultBase(r)) == refBaseMultEncoded(r)

suite "recodeScalarRadix16 (RFC-001 slice 4, white-box)":
  test "digit range is asymmetric: [-8,7] for positions 0..62, [-8,8] for 63":
    ## The black-box point-comparison tests above can pass on compensating
    ## recoding errors (a wrong digit paired with a wrong table entry that
    ## happens to land on the right point); this test inspects the digits
    ## directly, over random scalars from both domains geScalarmultBase
    ## must serve.
    var checked = 0

    for i in 0'u64 ..< 100:
      var s = prngScalar32(i)
      clampScalar(s)
      let digits = recodeScalarRadix16(s)
      for j in 0 ..< 63:
        check digits[j] >= -8
        check digits[j] <= 7
      check digits[63] >= -8
      check digits[63] <= 8
      inc checked

    for i in 0'u64 ..< 100:
      let r = prngReducedScalar32(i)
      let digits = recodeScalarRadix16(r)
      for j in 0 ..< 63:
        check digits[j] >= -8
        check digits[j] <= 7
      check digits[63] >= -8
      check digits[63] <= 8
      inc checked

    check checked == 200
