## scMulAdd: s = (a*b + c) mod L, ref10 sc_muladd port (scalar.nim).
##
## Vectors: all 27 joint combinations of (a, b, c) in {0, 1, L-1}^3, plus
## >=1000 random triples in [0, L). Both sets are generated by the checked-in
## oracle tests/vectors/gen_scmuladd_vectors.py (Python bigints, independent
## of sello's own arithmetic) into tests/vectors/scmuladd_test.json.

import std/[unittest, json, strutils]
import sello/scalar

const rawVectors = staticRead("../vectors/scmuladd_test.json")

proc hexToArray32(s: string): array[32, byte] =
  doAssert s.len == 64
  for i in 0 ..< 32:
    result[i] = byte(parseHexInt(s[2 * i .. 2 * i + 1]))

suite "scMulAdd":
  test "1*1 + 0 = 1 (RED anchor vector)":
    var a, b, c, expected: array[32, byte]
    a[0] = 1
    b[0] = 1
    expected[0] = 1
    check scMulAdd(a, b, c) == expected

  test "27 fixed joint combinations of (a, b, c) in {0, 1, L-1}^3":
    let root = parseJson(rawVectors)
    var checked = 0
    for v in root["fixed"]:
      let a = hexToArray32(v["a"].getStr)
      let b = hexToArray32(v["b"].getStr)
      let c = hexToArray32(v["c"].getStr)
      let expected = hexToArray32(v["expected"].getStr)
      check scMulAdd(a, b, c) == expected
      inc checked
    check checked == 27

  test "random triples from the seeded python3 oracle":
    let root = parseJson(rawVectors)
    let randomGroup = root["random"]
    var checked = 0
    for v in randomGroup["vectors"]:
      let a = hexToArray32(v["a"].getStr)
      let b = hexToArray32(v["b"].getStr)
      let c = hexToArray32(v["c"].getStr)
      let expected = hexToArray32(v["expected"].getStr)
      check scMulAdd(a, b, c) == expected
      inc checked
    check checked == randomGroup["count"].getInt
    check checked >= 1000
