## scMulAdd: s = (a*b + c) mod L, ref10 sc_muladd port (scalar.nim).
##
## Vectors: all 27 joint combinations of (a, b, c) in {0, 1, L-1}^3, plus
## >=1000 random triples in [0, L). Both sets are generated by the checked-in
## oracle tests/vectors/gen_scmuladd_vectors.py (Python bigints, independent
## of sello's own arithmetic) into tests/vectors/scmuladd_test.json.

import std/[unittest, json, strutils, osproc, os]
import nimcrypto/sha2
import sello/scalar
import sello/field

const rawVectors = staticRead("../vectors/scmuladd_test.json")

proc hexToArray32(s: string): array[32, byte] =
  doAssert s.len == 64
  for i in 0 ..< 32:
    result[i] = byte(parseHexInt(s[2 * i .. 2 * i + 1]))

proc cachedEncode(c: GeCached; invTwo: Fe): array[32, byte] =
  ## Canonical compressed encoding of the point cached in `c`, recovering
  ## affine X = (yPlusX - yMinusX)/2, Y = (yPlusX + yMinusX)/2 and reusing
  ## pointEncode (which only reads x/y/z, never t) to normalize away the
  ## projective Z-scaling. Needed because two different computational
  ## paths to the same point (this table's incremental doubling/addition
  ## vs. scalarmultVartime's 4-bit-window algorithm) generally land on different,
  ## equally-valid (X:Y:Z:T) representatives — raw limb/struct equality
  ## between them would be a false negative, not a real correctness check.
  var p: GeP3
  var sum, diff: Fe
  feAdd(sum, c.yPlusX, c.yMinusX)
  feSub(diff, c.yPlusX, c.yMinusX)
  feMul(p.y, sum, invTwo)
  feMul(p.x, diff, invTwo)
  p.z = c.z
  pointEncode(p)

suite "scMulAdd":
  test "1*1 + 0 = 1 (RED anchor vector)":
    var a, b, c, expected: array[32, byte]
    a[0] = 1
    b[0] = 1
    expected[0] = 1
    check scMulAdd(a, toSecretScalar(b), toSecretScalar(c)) == expected

  test "27 fixed joint combinations of (a, b, c) in {0, 1, L-1}^3":
    let root = parseJson(rawVectors)
    var checked = 0
    for v in root["fixed"]:
      let a = hexToArray32(v["a"].getStr)
      let b = hexToArray32(v["b"].getStr)
      let c = hexToArray32(v["c"].getStr)
      let expected = hexToArray32(v["expected"].getStr)
      check scMulAdd(a, toSecretScalar(b), toSecretScalar(c)) == expected
      inc checked
    check checked == 27

  test "random triples from the seeded python3 oracle":
    let root = parseJson(rawVectors)
    let randomGroup = root["random"]
    var checked = 0
    for v in randomGroup["vectors"]:
      let a = hexToArray32(v["a"].getStr)
      let b = hexToArray32(v["b"].getStr)
      let c = hexToArray32(v["c"].getStr)
      let expected = hexToArray32(v["expected"].getStr)
      check scMulAdd(a, toSecretScalar(b), toSecretScalar(c)) == expected
      inc checked
    check checked == randomGroup["count"].getInt
    check checked >= 1000

suite "GeBaseTable (RFC-001 slice 3)":
  test "row 0, column 0 is the base point B itself (RED anchor vector)":
    let b = geBasePoint()
    var expected: GeCached
    geP3ToCached(expected, b)
    check GeBaseTable[0][0] == expected

  test "every entry equals the runtime-computed multiple of B (standing guard)":
    ## GeBaseTable[i][j] must equal (j+1) * 16^(2*i) * B = (j+1) * 256^i * B.
    ##
    ## What this guard actually pins (review finding 10 flagged an earlier
    ## version of this comment for overstating its independence from
    ## scalarmultVartime — both sides ultimately bottom out in the same
    ## geAdd/geP2Dbl group-law primitives, so this is NOT an
    ## independent proof of the group law itself): (1) table-construction
    ## bookkeeping — buildBaseTable's per-row doubling/addition loop lands
    ## on the exact (j+1)*256^i*B the table's own indexing contract
    ## promises, not an off-by-one row/column or a wrong power of 256; (2)
    ## compile-time VM arithmetic agrees with the identical runtime
    ## arithmetic — buildBaseTable runs at compile time via Nim's VM, and a
    ## VM/runtime float-like divergence in the underlying int32/int64 limb
    ## ops would show up here as a mismatch; (3) cmovCached's constant-time
    ## select recovers the same table entries the compile-time build wrote,
    ## once decoded back to affine coordinates. The group-law correctness
    ## burden itself (that geAdd/geP2Dbl/scalarmultVartime compute the
    ## right curve arithmetic at all) is carried by the external RFC 8032 +
    ## Wycheproof vectors (test_ed25519.nim, test_wycheproof.nim) and, for
    ## geScalarmultBase specifically, the property-based agreement checks
    ## in test_properties_scalar.nim — not by this test. This repo has no
    ## CI, so this assertion re-verifies the compile-time table on every
    ## `scripts/test.sh` run rather than trusting the const-eval once.
    ## Compared via canonical point encoding (cachedEncode), not raw struct
    ## equality — see its doc comment for why.
    let b = geBasePoint()
    var two = Fe(limbs: [2'i32, 0, 0, 0, 0, 0, 0, 0, 0, 0])
    var invTwo: Fe
    feInvert(invTwo, two)
    var checked = 0
    for i in 0..<32:
      for j in 1..8:
        var scalarBytes: array[32, byte]
        scalarBytes[i] = byte(j)  # little-endian encoding of j * 256^i
        var refP3: GeP3
        scalarmultVartime(refP3, scalarBytes, b)
        check cachedEncode(GeBaseTable[i][j - 1], invTwo) == pointEncode(refP3)
        inc checked
    check checked == 32 * 8

suite "cmovCached (RFC-001 slice 3)":
  test "digit 0 selects the identity, with no special case":
    var r: GeCached
    cmovCached(r, GeBaseTable[0], 0)
    check r.yPlusX == FeOne
    check r.yMinusX == FeOne
    check r.z == FeOne
    check r.t2d == FeZero

  test "positive digits 1..8 select the matching table entry unchanged":
    for digit in 1..8:
      var r: GeCached
      cmovCached(r, GeBaseTable[0], int32(digit))
      check r == GeBaseTable[0][digit - 1]

  test "negative digits -1..-8 select the matching entry, negated":
    for digit in -8 .. -1:
      var r: GeCached
      cmovCached(r, GeBaseTable[0], int32(digit))
      let src = GeBaseTable[0][(-digit) - 1]
      var expectedT2d: Fe
      feNeg(expectedT2d, src.t2d)
      check r.yPlusX == src.yMinusX
      check r.yMinusX == src.yPlusX
      check r.z == src.z
      check r.t2d == expectedT2d

  test "every row of GeBaseTable agrees with cmovCached across all digits -8..8":
    for row in 0..<32:
      for digit in -8 .. 8:
        var r: GeCached
        cmovCached(r, GeBaseTable[row], int32(digit))
        if digit == 0:
          check r.yPlusX == FeOne
          check r.yMinusX == FeOne
          check r.z == FeOne
          check r.t2d == FeZero
        elif digit > 0:
          check r == GeBaseTable[row][digit - 1]
        else:
          let src = GeBaseTable[row][(-digit) - 1]
          var expectedT2d: Fe
          feNeg(expectedT2d, src.t2d)
          check r.yPlusX == src.yMinusX
          check r.yMinusX == src.yPlusX
          check r.z == src.z
          check r.t2d == expectedT2d

# ---------------------------------------------------------------------------
# geScalarmultBase (RFC-001 slice 4)
#
# Precondition under test throughout: bit 255 of the scalar clear — the
# WHOLE precondition (see scalar.nim's doc comment on recodeScalarRadix16).
# Both scalar domains that real signing exercises are covered:
#   - clamped secret-scalar shape (bit 255 clear, bit 254 set): RFC seed,
#     random clamped scalars, and the maximal clamped scalar (top byte
#     0x7F, the final-carry boundary).
#   - r-shaped nonces (reduced mod L, top three bits always clear since
#     L < 2^253): random reduced values and values just below L (the
#     bit-252 boundary region, L's own highest set bit).
# Every case is checked against the existing `scalarmultVartime` on the
# base point via pointEncode, not raw GeP3/GeCached equality — two
# algorithms reaching the same point generally land on different, equally
# valid projective representatives (same false-negative trap noted on the
# GeBaseTable standing-guard test above).
# ---------------------------------------------------------------------------

proc refBaseMultEncoded(s: array[32, byte]): array[32, byte] =
  var p: GeP3
  scalarmultVartime(p, s, geBasePoint())
  pointEncode(p)

proc prngScalar32(counter: uint64): array[32, byte] =
  ## Deterministic pseudorandom 32 bytes for test-vector generation only —
  ## not used for anything security-sensitive. SHA-512 counter mode so a
  ## failing case reproduces exactly from the printed counter.
  var counterBytes: array[8, byte]
  for i in 0 ..< 8:
    counterBytes[i] = byte((counter shr (8 * i)) and 0xFF'u64)
  var sha: sha512
  sha.init()
  sha.update(counterBytes)
  var digest: array[64, byte]
  sha.finish(digest)
  for i in 0 ..< 32: result[i] = digest[i]

proc prngReducedScalar32(counter: uint64): array[32, byte] =
  ## A random-looking scalar strictly < L, exactly the shape a real nonce
  ## r = scReduce(SHA-512(...)) has: top three bits always clear.
  var wide: array[64, byte]
  let lo = prngScalar32(2 * counter)
  let hi = prngScalar32(2 * counter + 1)
  for i in 0 ..< 32: wide[i] = lo[i]
  for i in 0 ..< 32: wide[32 + i] = hi[i]
  scReduce(result, wide)

proc decrementLE(b: array[32, byte]; amount: int): array[32, byte] =
  ## b - amount, treating b as little-endian; amount is small enough
  ## (< 256) that at most one borrow ever propagates past the first limb
  ## in the vectors this file constructs from L.
  result = b
  var borrow = amount
  var i = 0
  while borrow > 0:
    doAssert i < 32
    let cur = int(result[i]) - borrow
    if cur < 0:
      result[i] = byte(cur + 256)
      borrow = 1
    else:
      result[i] = byte(cur)
      borrow = 0
    inc i

suite "scalarmultVartime -- s = 0 (RFC-004 slice 7a finding)":
  ## Regression pin for a pre-existing bug discovered while cross-checking
  ## `geScalarmultCT` against this function at s=0: `started` never flips
  ## true for an all-zero scalar, so the loop body never assigns to `r`,
  ## and a freshly-declared `var r: GeP3` caller-side used to come back
  ## with Nim's implicit all-zero object fields -- (0:0:0:0), NOT the
  ## identity (0:1:1:0) -- rather than the mathematically correct [0]p.
  ## `RistrettoPoint`'s quotient `==` could not catch this (every
  ## cross-product collapses to 0 when x1=y1=0, so it degenerately treats
  ## the all-zero garbage as "equal to the identity" without it actually
  ## holding the identity's real coordinates); `pointEncode` comparison,
  ## used below and throughout this file, does not have that blind spot.
  ## Fixed by seeding `r` with the identity before the digit loop.
  test "[0]P equals the identity via pointEncode, for the base point":
    var r: GeP3
    scalarmultVartime(r, default(array[32, byte]), geBasePoint())
    var identity: GeP3
    identity.y = FeOne; identity.z = FeOne
    check pointEncode(r) == pointEncode(identity)

  test "[0]P equals the identity via pointEncode, for an arbitrary non-base point":
    var arbitrary: GeP3
    var five: array[32, byte]
    five[0] = 5
    scalarmultVartime(arbitrary, five, geBasePoint())
    var r: GeP3
    scalarmultVartime(r, default(array[32, byte]), arbitrary)
    var identity: GeP3
    identity.y = FeOne; identity.z = FeOne
    check pointEncode(r) == pointEncode(identity)

suite "geScalarmultBase (RFC-001 slice 4)":
  test "[1]B equals the base point itself (RED anchor vector)":
    var s: array[32, byte]
    s[0] = 1
    check pointEncode(geScalarmultBase(toSecretScalar(s))) == pointEncode(geBasePoint())

  test "clamped domain: RFC 8032 test-vector-1 seed, expanded and clamped":
    # RFC 8032 Section 7.1 TEST 1 secret key seed (also tv1_sk in
    # test_ed25519.nim) — a real clamped scalar `a` as `sign` will derive
    # it: a = clampScalar(SHA-512(seed)[0..31]).
    let seed: array[32, byte] = [
      0x9d'u8, 0x61, 0xb1, 0x9d, 0xef, 0xfd, 0x5a, 0x60,
      0xba, 0x84, 0x4a, 0xf4, 0x92, 0xec, 0x2c, 0xc4,
      0x44, 0x49, 0xc5, 0x69, 0x7b, 0x32, 0x69, 0x19,
      0x70, 0x3b, 0xac, 0x03, 0x1c, 0xae, 0x7f, 0x60
    ]
    var sha: sha512
    sha.init()
    sha.update(seed)
    var expanded: array[64, byte]
    sha.finish(expanded)
    var a: array[32, byte]
    for i in 0 ..< 32: a[i] = expanded[i]
    clampScalar(a)
    check pointEncode(geScalarmultBase(toSecretScalar(a))) == refBaseMultEncoded(a)

  test "clamped domain: 100 random clamped scalars match scalarmultVartime":
    var checked = 0
    for i in 0'u64 ..< 100:
      var s = prngScalar32(i)
      clampScalar(s)
      check pointEncode(geScalarmultBase(toSecretScalar(s))) == refBaseMultEncoded(s)
      inc checked
    check checked == 100

  test "clamped domain: maximal clamped scalar (top byte 0x7F, final-carry boundary)":
    var s: array[32, byte]
    for i in 0 ..< 32: s[i] = 0xFF
    clampScalar(s)
    check s[0] == 0xF8
    check s[31] == 0x7F
    check pointEncode(geScalarmultBase(toSecretScalar(s))) == refBaseMultEncoded(s)

  test "r-shaped domain: 100 random reduced-mod-L scalars match scalarmultVartime":
    var checked = 0
    for i in 0'u64 ..< 100:
      let r = prngReducedScalar32(i)
      check scIsCanonical(r)
      check pointEncode(geScalarmultBase(toSecretScalar(r))) == refBaseMultEncoded(r)
      inc checked
    check checked == 100

  test "r-shaped domain: values just below L (bit-252 boundary region)":
    for amount in [1, 2, 3, 17, 255]:
      let r = decrementLE(L, amount)
      check scIsCanonical(r)
      check pointEncode(geScalarmultBase(toSecretScalar(r))) == refBaseMultEncoded(r)

# ---------------------------------------------------------------------------
# geScalarmultCT (RFC-004 slice 7a) -- CT variable-base scalar
# multiplication: the uniform 256-doubling interleaved ladder over a
# runtime-built 8-entry table. Same false-negative trap as
# geScalarmultBase above (two algorithms reaching the same point generally
# land on different, equally-valid projective representatives), so every
# check compares via pointEncode against scalarmultVartime -- exercised
# here against ARBITRARY points (not the base point), since this is a
# variable-base operation and geScalarmultBase's own suite above already
# covers the base-point case exhaustively (and `ristretto.nim`'s own tests
# cross-check the base-point case a second, higher-level way: `[s]B` via
# `geScalarmultCT` must equal `[s]B` via `geScalarmultBase`).
# ---------------------------------------------------------------------------

proc refVarScalarmultEncoded(s: array[32, byte]; p: GeP3): array[32, byte] =
  var r: GeP3
  scalarmultVartime(r, s, p)
  pointEncode(r)

proc arbitraryPoint(seed: uint64): GeP3 =
  ## A non-identity, non-base point: seed*B via the already-vector-trusted
  ## scalarmultVartime, so the point itself carries no correctness
  ## assumption from the code under test.
  scalarmultVartime(result, prngScalar32(seed), geBasePoint())

suite "geScalarmultCT (RFC-004 slice 7a)":
  test "[1]P equals P itself (RED anchor vector)":
    let p = arbitraryPoint(1000)
    var s: array[32, byte]
    s[0] = 1
    check pointEncode(geScalarmultCT(toSecretScalar(s), p)) == pointEncode(p)

  test "[0]P equals the identity, matching scalarmultVartime":
    let p = arbitraryPoint(1001)
    let s = default(array[32, byte])
    check pointEncode(geScalarmultCT(toSecretScalar(s), p)) == refVarScalarmultEncoded(s, p)

  test "clamped domain: RFC 8032 test-vector-1 seed, expanded and clamped, against an arbitrary point":
    let seed: array[32, byte] = [
      0x9d'u8, 0x61, 0xb1, 0x9d, 0xef, 0xfd, 0x5a, 0x60,
      0xba, 0x84, 0x4a, 0xf4, 0x92, 0xec, 0x2c, 0xc4,
      0x44, 0x49, 0xc5, 0x69, 0x7b, 0x32, 0x69, 0x19,
      0x70, 0x3b, 0xac, 0x03, 0x1c, 0xae, 0x7f, 0x60
    ]
    var sha: sha512
    sha.init()
    sha.update(seed)
    var expanded: array[64, byte]
    sha.finish(expanded)
    var a: array[32, byte]
    for i in 0 ..< 32: a[i] = expanded[i]
    clampScalar(a)
    let p = arbitraryPoint(1002)
    check pointEncode(geScalarmultCT(toSecretScalar(a), p)) == refVarScalarmultEncoded(a, p)

  test "clamped domain: 50 random clamped scalars match scalarmultVartime, over 5 distinct points":
    var checked = 0
    for pi in 0'u64 ..< 5:
      let p = arbitraryPoint(2000 + pi)
      for i in 0'u64 ..< 50:
        var s = prngScalar32(pi * 1000 + i)
        clampScalar(s)
        check pointEncode(geScalarmultCT(toSecretScalar(s), p)) == refVarScalarmultEncoded(s, p)
        inc checked
    check checked == 250

  test "clamped domain: maximal clamped scalar (top byte 0x7F, final-carry boundary)":
    var s: array[32, byte]
    for i in 0 ..< 32: s[i] = 0xFF
    clampScalar(s)
    check s[0] == 0xF8
    check s[31] == 0x7F
    let p = arbitraryPoint(1003)
    check pointEncode(geScalarmultCT(toSecretScalar(s), p)) == refVarScalarmultEncoded(s, p)

  test "r-shaped domain: 50 random reduced-mod-L scalars match scalarmultVartime, over 5 distinct points":
    var checked = 0
    for pi in 0'u64 ..< 5:
      let p = arbitraryPoint(3000 + pi)
      for i in 0'u64 ..< 50:
        let r = prngReducedScalar32(pi * 1000 + i)
        check scIsCanonical(r)
        check pointEncode(geScalarmultCT(toSecretScalar(r), p)) == refVarScalarmultEncoded(r, p)
        inc checked
    check checked == 250

  test "r-shaped domain: values just below L (bit-252 boundary region)":
    let p = arbitraryPoint(1004)
    for amount in [1, 2, 3, 17, 255]:
      let r = decrementLE(L, amount)
      check scIsCanonical(r)
      check pointEncode(geScalarmultCT(toSecretScalar(r), p)) == refVarScalarmultEncoded(r, p)

  test "agrees with geScalarmultBase at the base point itself (cross-check between the two CT ladders)":
    for i in 0'u64 ..< 20:
      var s = prngScalar32(4000 + i)
      clampScalar(s)
      let viaCT = geScalarmultCT(toSecretScalar(s), geBasePoint())
      let viaFixedBase = geScalarmultBase(toSecretScalar(s))
      check pointEncode(viaCT) == pointEncode(viaFixedBase)

suite "recodeScalarRadix16 (RFC-001 slice 4, white-box)":
  test "digit range is asymmetric: [-8,7] for positions 0..62, [-8,8] for 63":
    ## The black-box point-comparison tests above can pass on compensating
    ## recoding errors (a wrong digit paired with a wrong table entry that
    ## happens to land on the right point); this test inspects the digits
    ## directly, over random scalars from both domains geScalarmultBase
    ## must serve.
    var checked = 0

    for i in 0'u64 ..< 100:
      var s = prngScalar32(i)
      clampScalar(s)
      let digits = recodeScalarRadix16(s)
      for j in 0 ..< 63:
        check digits[j] >= -8
        check digits[j] <= 7
      check digits[63] >= -8
      check digits[63] <= 8
      inc checked

    for i in 0'u64 ..< 100:
      let r = prngReducedScalar32(i)
      let digits = recodeScalarRadix16(r)
      for j in 0 ..< 63:
        check digits[j] >= -8
        check digits[j] <= 7
      check digits[63] >= -8
      check digits[63] <= 8
      inc checked

    check checked == 200

# ---------------------------------------------------------------------------
# geP2Dbl (RFC-002 slice 5 finding): single-call isolation.
#
# Every call site of geP2Dbl in scalar.nim -- scalarmultVartime's per-nibble
# doubling loop (exactly 4 consecutive calls) and geP3Double's own two
# callers, buildBaseTable (8 consecutive calls per row) and
# geScalarmultBase (4 consecutive calls to scale by 16) -- invokes it an
# EVEN number of times before the result is ever compared against anything.
# A systematic sign error that negates geP2Dbl's output (Dbl'(P) = -Dbl(P),
# i.e. the Edwards-curve point negation (-x, y)) is therefore invisible at
# every existing call site: two (or four, or eight) such errors compose
# back to the correct point, since (-1)^even = 1. RFC-002 slice 5's curated
# mutation-testing catalog (tests/mutation/mutants/S02_gep2dbl_xplusy_sign_
# flip.mutant, feAdd -> feSub on the "X+Y" line) caught exactly this: it
# survived scripts/test.sh's full suite untouched, because nothing in that
# suite calls geP2Dbl an odd number of times before checking the result.
# This test closes the gap directly, by isolating a single (odd-count)
# call -- doubling the base point once and checking it against [2]B,
# computed independently via the already-vector-trusted scalarmultVartime
# -- rather than relying on some other test happening to hit an odd count.
# ---------------------------------------------------------------------------

suite "geP2Dbl (RFC-002 slice 5 finding: single-call isolation)":
  test "a single geP2Dbl call on the base point equals [2]B":
    let b = geBasePoint()
    var p2: GeP2
    geP3ToP2(p2, b)
    var d: GeP1P1
    geP2Dbl(d, p2)
    var doubled: GeP3
    geP1P1ToP3(doubled, d)

    var two: array[32, byte]
    two[0] = 2
    check pointEncode(doubled) == refBaseMultEncoded(two)

  test "a single geP2Dbl call on 100 random points equals scalarmultVartime([2], p)":
    ## Generalizes the base-point anchor above across random curve points
    ## (reached via scalarmultVartime on random scalars, not just B), so
    ## the isolation guard doesn't depend on any base-point-specific
    ## coincidence.
    var checked = 0
    for i in 0'u64 ..< 100:
      let s = prngScalar32(i)
      var p3: GeP3
      scalarmultVartime(p3, s, geBasePoint())
      var p2: GeP2
      geP3ToP2(p2, p3)
      var d: GeP1P1
      geP2Dbl(d, p2)
      var doubled: GeP3
      geP1P1ToP3(doubled, d)

      var two: array[32, byte]
      two[0] = 2
      var expected: GeP3
      scalarmultVartime(expected, two, p3)
      check pointEncode(doubled) == pointEncode(expected)
      inc checked
    check checked == 100

# ---------------------------------------------------------------------------
# SecretScalar type boundary (round-3 finding A3): "a secret scalar can
# never reach scalarmultVartime" is a compile error, not a naming
# convention -- see SecretScalar's own doc comment above for the full
# reasoning.
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# geAdd edge cases (round-3 fix batch B, finding B5): P+P and P+(-P) through
# the unified-addition formula directly. `geScalarmultBase`'s radix-16 loop
# and `scalarmultVartime`'s 4-bit-window loop never feed `geAdd` an operand
# equal (or equal-and-negated) to its accumulator by construction (doubling
# always goes through the separate `geP2Dbl` path; a digit of exactly 0
# short-circuits to the identity via `cmovCached`, never calling `geAdd` at
# all) -- so these two edge cases go untouched by every other test in this
# suite, including the mutation-testing catalog's S04/S05 `geAdd` sign-flip
# mutants (killed via other call paths, not this one). `Ed25519D2` (the
# "2d*Tq*T" term) and the "2*Z*Zq" term are exactly the two additions
# `geAdd`'s doc comment above marks as ref10's unified-addition trick for
# handling P+P without a separate doubling formula; a broken sign on either
# is invisible unless something calls `geAdd` with equal or negated inputs.
# ---------------------------------------------------------------------------

proc negateP3(p: GeP3): GeP3 =
  ## -P = (-x, y, z, -t) in extended coordinates -- still on the curve
  ## (t' = (-x)*y/z = -(x*y/z) = -t stays consistent with the extended
  ## coordinate invariant).
  feNeg(result.x, p.x)
  result.y = p.y
  result.z = p.z
  feNeg(result.t, p.t)

proc geAddP3(p, q: GeP3): GeP3 =
  var cachedQ: GeCached
  geP3ToCached(cachedQ, q)
  var r: GeP1P1
  geAdd(r, p, cachedQ)
  geP1P1ToP3(result, r)

proc geP2DblP3(p: GeP3): GeP3 =
  var p2: GeP2
  geP3ToP2(p2, p)
  var d: GeP1P1
  geP2Dbl(d, p2)
  geP1P1ToP3(result, d)

const IdentityEncoded: array[32, byte] = block:
  var b: array[32, byte]
  b[0] = 1
  b

suite "geAdd edge cases (round-3 fix batch B, finding B5)":
  test "P + P via geAdd agrees with geP2Dbl's doubling of the base point":
    let p = geBasePoint()
    check pointEncode(geAddP3(p, p)) == pointEncode(geP2DblP3(p))

  test "P + P via geAdd agrees with geP2Dbl's doubling, over 20 random points":
    var checked = 0
    for i in 0'u64 ..< 20:
      let s = prngScalar32(i)
      var p: GeP3
      scalarmultVartime(p, s, geBasePoint())
      check pointEncode(geAddP3(p, p)) == pointEncode(geP2DblP3(p))
      inc checked
    check checked == 20

  test "P + (-P) via geAdd encodes to the identity, for the base point":
    let p = geBasePoint()
    check pointEncode(geAddP3(p, negateP3(p))) == IdentityEncoded

  test "P + (-P) via geAdd encodes to the identity, over 20 random points":
    var checked = 0
    for i in 0'u64 ..< 20:
      let s = prngScalar32(i)
      var p: GeP3
      scalarmultVartime(p, s, geBasePoint())
      check pointEncode(geAddP3(p, negateP3(p))) == IdentityEncoded
      inc checked
    check checked == 20

suite "SecretScalar - scalarmultVartime type boundary (compile-time)":
  test "SecretScalar has no implicit converter to array[32, byte]":
    ## `compiles()` CAN see this one (an ordinary type mismatch, unlike the
    ## `=copy`/sink violations tested via subprocess elsewhere in this
    ## suite) -- pinned directly first, cheaply, before the subprocess
    ## fixture below re-confirms it as a literal compiler diagnostic for
    ## consistency with this directory's established methodology.
    check(not compiles(block:
      var r: GeP3
      let secretScalar = toSecretScalar(default(array[32, byte]))
      let p = geBasePoint()
      scalarmultVartime(r, secretScalar, p)
    ))

  test "scalarmultVartime(r, secretScalar, p) is rejected (subprocess compile)":
    ## Same subprocess-`nim c` methodology as `test_signing.nim`'s
    ## `Keypair`/`Seed` copy checks and `test_x25519.nim`'s ephemeral
    ## fixtures: a real compile of a deliberately-invalid, checked-in
    ## fixture, asserted to fail. `tests/unit/fixtures/
    ## reject_secretscalar_vartime.nim`'s own doc comment explains why this
    ## particular error class is ALSO visible to `compiles()` above --
    ## included regardless, as the literal pinned diagnostic.
    let fixture = currentSourcePath().parentDir / "fixtures" / "reject_secretscalar_vartime.nim"
    let repoRoot = currentSourcePath().parentDir.parentDir.parentDir
    let cmd = "nim c --hints:off --nimcache:" &
      (repoRoot / "build" / "nimcache_reject_secretscalar_vartime") & " " & fixture
    let (output, exitCode) = execCmdEx(cmd, workingDir = repoRoot)
    check exitCode != 0
    check "type mismatch" in output
